### PR TITLE
add Sign Up page design

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add the code for the design of Sign Up page

In this PR, **156 additions and 58 deletions** lines of code
- some files contain only 5 to 6 lines of code
- you can avoid to review CSS and Backend related files

#### [Live URL](https://react-inclusive-mart-git-page-sign-up-hsnice16.vercel.app/sign-up/user)
image

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
The code looks clean and readable. Learned a few things from your code!

I liked how you have divided form elements into different components.

Just one thing. While typing the password. Both password eye icons are visible. Remove/Hide one of them.

image

**Comment by hsnice16** [comment]
> The code looks clean and readable. Learned a few things from your code!
> 
> I liked how you have divided form elements into different components.
> 
> Just one thing. While typing the password. Both password eye icons are visible. Remove/Hide one of them.
> 
> image

Thanks for pointing this out. Actually, this comes on Edge and IE only. But I have pushed the code to not display them on these too.

**Review by b0llu — APPROVED** [review]
Nothing to suggest. Good work on using proptypes!

**Comment by hsnice16** [comment]
Thanks for reviewing.

**Review by abhisheksahani-nova — APPROVED** [review]
Your code is clean and way you have divided your form into small components  can be reuseable, great work.

**Pull request merged**
