### PR TITLE
add SignIn, SignUp and SignOut functionality

### PR DESCRIPTION
**Pull request by hsnice16**
### This PR will add code for the functionality of Sign In, Sign Up, and Sign Out functionality

In this PR, **572 additions and 58 deletions** lines of code
- Some files contain only 5 to 6 lines of code
- If you don't prefer you can avoid to review CSS and Backend related files

#### [Live Site](https://react-inclusive-mart-oijnd0y4y-hsnice16.vercel.app/)

---

To Check Sign In functionality, you can use
```
email: johndoe@gmail.com
password: johnDoe123
```

For Sign Up, you can add any dummy data of your choice.

### CODE REVIEW

**Review by keshavkumar-in — APPROVED** [review]
Overall UI and code looks good and clean to me. Just had a suggestion, for mobile screen your logout button is too close to the search button, you can place it along side the cart and Wishlist icons. Other observation is that you can show Wishlist icon to only logged in user.

Other than these good to merge.

**Review by vrx29 — APPROVED** [review]
Nice work your code is clean and well structured. Just one suggestion on the cart page the footer is moving upwards if you can make it fixed to bottom it will be good in terms of UI.

**Comment by hsnice16** [comment]
> Overall UI and code looks good and clean to me. Just had a suggestion, for mobile screen your logout button is too close to the search button, you can place it along side the cart and Wishlist icons. Other observation is that you can show Wishlist icon to only logged in user.
> 
> Other than these good to merge.

Thanks, Keshav for suggesting these changes, will look into these after the implementation of all the basic requirements.

**Review by Developers-codz — APPROVED** [review]
Clean and readable code, Good to merge

**Comment by hsnice16** [comment]
> Nice work your code is clean and well structured. Just one suggestion on the cart page the footer is moving upwards if you can make it fixed to bottom it will be good in terms of UI.

Thankyou for checking this Vineet, yes I have to implement Cart and Wishlist page after that this will be fine.

**Comment by hsnice16** [comment]
Thankyou for reviewing.

**Pull request merged**
